export const AcaoProjeto = {
    OBTER_PROJETOS : "OBTER_PROJETOS",
    CADASTRAR_PROJETO : "CADASTRAR_PROJETO",
    ALTERAR_PROJETO : "ALTERAR_PROJETO",
    REMOVER_PROJETO : "REMOVER_PROJETO",
};

export const AcaoTarefas = {
    OBTER_TAREFAS : "OBTER_TAREFAS",
    CADASTRAR_TAREFA : "CADASTRAR_TAREFA",
    ALTERAR_TAREFA : "ALTERAR_TAREFA",
    REMOVER_TAREFA : "REMOVER_TAREFA",
};